// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PicPool.Infrastructure.Data;

#nullable disable

namespace PicPool.Infrastructure.Migrations
{
    [DbContext(typeof(PicPoolDbContext))]
    [Migration("20260526162214_AfegirSourceUrlAImatge")]
    partial class AfegirSourceUrlAImatge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PicPool.Domain.Entities.Imatge", b =>
                {
                    b.Property<string>("ImatgePK")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataPujada")
                        .HasColumnType("datetime2");

                    b.Property<long>("MidaBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("NomOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RutaStorage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TipusMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuariPujadorPK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ImatgePK");

                    b.HasIndex("UsuariPujadorPK");

                    b.ToTable("Imatges");
                });

            modelBuilder.Entity("PicPool.Domain.Entities.Pla", b =>
                {
                    b.Property<string>("PlaPK")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Actiu")
                        .HasColumnType("bit");

                    b.Property<long>("LimitEmmagatzematgeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("LimitImatges")
                        .HasColumnType("int");

                    b.Property<int>("LimitSales")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preu")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PlaPK");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("PicPool.Domain.Entities.Sala", b =>
                {
                    b.Property<string>("SalaPK")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCreacio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExpiracio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TokenAcces")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsuariCreadorPK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SalaPK");

                    b.HasIndex("TokenAcces")
                        .IsUnique();

                    b.HasIndex("UsuariCreadorPK");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("PicPool.Domain.Entities.SalaImatge", b =>
                {
                    b.Property<string>("ImatgeSalaPK")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImatgePK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalaPK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ImatgeSalaPK");

                    b.HasIndex("ImatgePK");

                    b.HasIndex("SalaPK", "ImatgePK")
                        .IsUnique();

                    b.ToTable("SalaImatges");
                });

            modelBuilder.Entity("PicPool.Domain.Entities.SalaUsuari", b =>
                {
                    b.Property<string>("SalaUsuariPK")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DataUnio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PotDescarregar")
                        .HasColumnType("bit");

                    b.Property<bool>("PotEliminarPropies")
                        .HasColumnType("bit");

                    b.Property<bool>("PotEliminarQualsevol")
                        .HasColumnType("bit");

                    b.Property<bool>("PotGestionarSala")
                        .HasColumnType("bit");

                    b.Property<bool>("PotPujar")
                        .HasColumnType("bit");

                    b.Property<bool>("PotVeure")
                        .HasColumnType("bit");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalaPK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuariPK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SalaUsuariPK");

                    b.HasIndex("UsuariPK");

                    b.HasIndex("SalaPK", "UsuariPK")
                        .IsUnique();

                    b.ToTable("SalaUsuaris");
                });

            modelBuilder.Entity("PicPool.Domain.Entities.Usuari", b =>
                {
                    b.Property<string>("UsuariPK")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Actiu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UsuariPK");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuaris");
                });

            modelBuilder.Entity("PicPool.Domain.Entities.UsuariPla", b =>
                {
                    b.Property<string>("UsuariPlaPK")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Actiu")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataFi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInici")
                        .HasColumnType("datetime2");

                    b.Property<long>("EspaiConsumitBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("ImatgesPujades")
                        .HasColumnType("int");

                    b.Property<string>("PlaPK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SalesCreades")
                        .HasColumnType("int");

                    b.Property<string>("UsuariPK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuariPlaPK");

                    b.HasIndex("PlaPK");

                    b.HasIndex("UsuariPK");

                    b.ToTable("UsuariPlans");
                });

            modelBuilder.Entity("PicPool.Domain.Entities.Imatge", b =>
                {
                    b.HasOne("PicPool.Domain.Entities.Usuari", null)
                        .WithMany("ImatgesPujades")
                        .HasForeignKey("UsuariPujadorPK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PicPool.Domain.Entities.Sala", b =>
                {
                    b.HasOne("PicPool.Domain.Entities.Usuari", "UsuariCreador")
                        .WithMany("SalesCreades")
                        .HasForeignKey("UsuariCreadorPK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuariCreador");
                });

            modelBuilder.Entity("PicPool.Domain.Entities.SalaImatge", b =>
                {
                    b.HasOne("PicPool.Domain.Entities.Imatge", "Imatge")
                        .WithMany()
                        .HasForeignKey("ImatgePK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicPool.Domain.Entities.Sala", "Sala")
                        .WithMany("ImatgesSala")
                        .HasForeignKey("SalaPK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imatge");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("PicPool.Domain.Entities.SalaUsuari", b =>
                {
                    b.HasOne("PicPool.Domain.Entities.Sala", null)
                        .WithMany("UsuarisSala")
                        .HasForeignKey("SalaPK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PicPool.Domain.Entities.Usuari", null)
                        .WithMany("SalesUsuari")
                        .HasForeignKey("UsuariPK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PicPool.Domain.Entities.UsuariPla", b =>
                {
                    b.HasOne("PicPool.Domain.Entities.Pla", null)
                        .WithMany()
                        .HasForeignKey("PlaPK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PicPool.Domain.Entities.Usuari", null)
                        .WithMany("UsuariPlans")
                        .HasForeignKey("UsuariPK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PicPool.Domain.Entities.Sala", b =>
                {
                    b.Navigation("ImatgesSala");

                    b.Navigation("UsuarisSala");
                });

            modelBuilder.Entity("PicPool.Domain.Entities.Usuari", b =>
                {
                    b.Navigation("ImatgesPujades");

                    b.Navigation("SalesCreades");

                    b.Navigation("SalesUsuari");

                    b.Navigation("UsuariPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
